title: "Naveen&nbsp;Kumar&nbsp;Rajesh"
logo: "/assets/images/Photo.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <p align="center">
  <a href="mailto:rajeshn@uci.edu">Email</a> |
  <a href="https://www.linkedin.com/in/messinavu10/">LinkedIn</a> |
  <a href="https://github.com/Messinavu10">GitHub</a>
  </p>
  
  I am a Data Scientist with close to 2 years of experience in DevOps, MLOps, and Data Analytics. I hold an M.S. in Data Science from the University of California, Irvine, and a B.S. in Computer Science from the University of San Diego.
  <br><br>
  I am passionate about building scalable machine learning pipelines, deploying production-ready models, and leveraging data-driven insights to solve real-world problems. I am currently seeking opportunities in MLOps, DevOps, or Data Science where I can contribute to impactful projects.
  <br><br>
  
theme: jekyll-theme-minimal
